server:
  port: ${SERVER_PORT:8017}

spring:
  redis:
    host: 192.168.1.163
    port: 6379
    database: 2         # 选择哪个库，默认0库
    timeout: 10000ms    # 连接超时时间
    jedis:
      pool:
        # 最大连接数，默认8
        max-active: 1024
        # 最大连接阻塞等待时间，单位毫秒，默认-1ms
        max-wait: 10000ms
        # 最大空闲连接，默认8
        max-idle: 200
        # 最小空闲连接，默认0
        min-idle: 5

#配置日志
logging:
  config: classpath:logback-spring.xml
  level:
    # root: ERROR
    # com.example.redisplus: error
    # com.example.redisplus: debug
    com.example.redisplus.seckill: error