# 本次构建的阶段：build package
stages:
 - build
 - package
 - deploy


variables:
  IMAGES: "hub.03in.com:5002/ranmufei/fitmgr-quota:v3"
  PRO_PATH: "fitmgr-quota"
  # 镜像：地址
# 构建 Job
build:
  stage: build  
  image: ranmufei/maven:latest
  script:
  - echo "=============== 环境变量输出 ==============="
  - echo "镜像：$IMAGES"
  - echo "代码质量检查"
  - cd ${PRO_PATH} && sh ./sonar.sh
# 打包
package:
  image: ranmufei/maven:latest
  stage: package
  script:
  - echo "=============== 	开始   ==============="
  - cd ${PRO_PATH}
  
  - echo "===================打包========================="
  - mvn package -Dmaven.test.skip=true
  - cd fitmgr-quota-biz && ls  -all

  artifacts:
      name:  "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
      paths:
       - ${PRO_PATH}/fitmgr-quota-biz/target/*
# 部署
deploy:
  stage: deploy
  script:
  - echo "----------		打包结果 ma ster ---------------------"
  - ls -all
 # - tar -zcvf 1128.tar.gz target 
  - ls
  
  - docker ps
  - docker images
  - docker info
  - cd ${PRO_PATH} && ls -all
  - echo "======			执行docker 打包 ====="
  - docker build -t $IMAGES .
  - docker images|grep ${PRO_PATH}
  - docker login hub.03in.com:5002 -u ranmufei -p cqsyyxydxsyc6z
  - docker push $IMAGES
  - echo "================执行部署================="
  - cd ../ && chmod +x ./install.sh && sh ./install.sh "$IMAGES"
 # - sshpass -p admin123456 scp 1128.tar.gz root@192.168.1.174:/root/
 
 
 
 