security:
  oauth2:
    client:
      client-id: ENC(Qw+cUczMH1ywGgwWt1AA3g==)
      client-secret: ENC(Qw+cUczMH1ywGgwWt1AA3g==)
      scope: server
      ignore-urls:
        - /**
        - /sop/routes
        - /druid/**
        - /actuator/**
        - /v2/api-docs

spring:
  redis:
    host: 192.168.1.175
    port: 6379
    database: 2
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${MYSQL-USER:root}
      password: ${MYSQL-PWD:123456}
      url: jdbc:mysql://${MYSQL-HOST:192.168.1.174}:${MYSQL-PORT:3037}/${MYSQL-DB:iot_core}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 10000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

minio:
  url: http://192.168.1.174:9000
  access-key: linksame
  secret-key: linksame

pgsql:
  url: jdbc:postgresql://192.168.1.174:5432/postgres
  user: postgres
  password: 123456