## spring security 配置
security:
  oauth2:
    client:
      client-id: ENC(Qw+cUczMH1ywGgwWt1AA3g==)
      client-secret: ENC(Qw+cUczMH1ywGgwWt1AA3g==)
      scope: server
      ignore-urls:
        - /druid/**
        - /sop/routes
        - /actuator/**
        - /v2/api-docs
        - /**
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${MYSQL-USER:root}
      password: ${MYSQL-PWD:123456}
      url: jdbc:mysql://${MYSQL-HOST:iot-mysql}:${MYSQL-PORT:3037}/${MYSQL-DB:iot_bim}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 10000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
bim:
  client:
    host: http://${BIM-HOST:192.168.1.174}:${BIM-PORT:8085}/bimserverwar-1.5.182
    username: ${BIM-USERNAME:test@qq.com}
    password: ${BIM-PASSWORD:123456}

# 文件系统 (提供测试环境，不要乱传)
minio:
  url: http://${MINIO-HOST:iot-minio}:${MINIO-PORT:9000}
  access-key: ${MINIO-ACCESS-KEY:linksame}
  secret-key: ${MINIO-SECRET-KEY:linksame}

# Logger Config
logging:
  level:
    com.hzcloud.linksme.admin.mapper: debug