## spring security 配置
security:
  oauth2:
    client:
      client-id: ENC(Qw+cUczMH1ywGgwWt1AA3g==)
      client-secret: ENC(Qw+cUczMH1ywGgwWt1AA3g==)
      scope: server
      ignore-urls:
        - /druid/**
        - /sop/routes
        - /actuator/**
        - /v2/api-docs
        - /outbound/invite

# 数据源
spring:
  # 忽略null字段
  jackson:
    default-property-inclusion: non_null
  #  kafka:
  #    bootstrap-servers: ${KAFKA-HOST:192.168.1.174}:${KAFKA-PORT:9092}
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${MYSQL-USER:root}
      password: ${MYSQL-PWD:123456}
      url: jdbc:mysql://${MYSQL-HOST:iot-mysql}:${MYSQL-PORT:3037}/${MYSQL-DB:iot_visitors}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 10000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

# 文件系统 (提供测试环境，不要乱传)
minio:
  url: http://192.168.1.174:9000
  access-key: linksame
  secret-key: linksame

# Logger Config
logging:
  level:
    com.hzcloud.linksme.admin.mapper: debug

# 租户表维护
iot:
  tenant:
    column: tenant_id
    tables:
      - visitors_department
      - visitors_device
      - visitors_invite
      - visitors_outbound
      - visitors_recording
      - visitors_alarm