CREATE TABLE "PURCHASE"."COMMON_OPTIONS"
(
"id" BIGINT NOT NULL,
"dict_code" VARCHAR2(64),
"dict_name" VARCHAR2(1000),
"dict_desc" VARCHAR2(512),
"parent_id" VARCHAR2(64),
"group_code" VARCHAR2(200),
"del_flag" TINYINT DEFAULT 0 NOT NULL,
"create_time" DATETIME(0) DEFAULT CURRENT_TIMESTAMP NOT NULL,
"group_name" VARCHAR(200) DEFAULT NULL,
"moudle_code" VARCHAR2(2048),
"additional_info" TEXT,
NOT CLUSTER PRIMARY KEY("id")) STORAGE(ON "PURCHASE", CLUSTERBTR);
COMMENT ON TABLE "PURCHASE"."COMMON_OPTIONS" IS '业务字典表';
COMMENT ON COLUMN "PURCHASE"."COMMON_OPTIONS"."id" IS 'id';
COMMENT ON COLUMN "PURCHASE"."COMMON_OPTIONS"."dict_code" IS '编码';
COMMENT ON COLUMN "PURCHASE"."COMMON_OPTIONS"."dict_name" IS '名称';
COMMENT ON COLUMN "PURCHASE"."COMMON_OPTIONS"."dict_desc" IS '描述';
COMMENT ON COLUMN "PURCHASE"."COMMON_OPTIONS"."parent_id" IS '父节点(dict_code)';
COMMENT ON COLUMN "PURCHASE"."COMMON_OPTIONS"."group_code" IS '分组';
COMMENT ON COLUMN "PURCHASE"."COMMON_OPTIONS"."moudle_code" IS '业务功能模块';